// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: litellm/v1/user.proto

package litellmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_litellm_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_litellm_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_litellm_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_litellm_v1_user_proto protoreflect.FileDescriptor

const file_litellm_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x15litellm/v1/user.proto\x12\n" +
	"litellm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04timeB\x95\x01\n" +
	"\x0ecom.litellm.v1B\tUserProtoP\x01Z/github.com/wagnerjt/go-mcp/litellm/v1;litellmv1\xa2\x02\x03LXX\xaa\x02\n" +
	"Litellm.V1\xca\x02\n" +
	"Litellm\\V1\xe2\x02\x16Litellm\\V1\\GPBMetadata\xea\x02\vLitellm::V1b\x06proto3"

var (
	file_litellm_v1_user_proto_rawDescOnce sync.Once
	file_litellm_v1_user_proto_rawDescData []byte
)

func file_litellm_v1_user_proto_rawDescGZIP() []byte {
	file_litellm_v1_user_proto_rawDescOnce.Do(func() {
		file_litellm_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_litellm_v1_user_proto_rawDesc), len(file_litellm_v1_user_proto_rawDesc)))
	})
	return file_litellm_v1_user_proto_rawDescData
}

var file_litellm_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_litellm_v1_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: litellm.v1.User
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_litellm_v1_user_proto_depIdxs = []int32{
	1, // 0: litellm.v1.User.time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_litellm_v1_user_proto_init() }
func file_litellm_v1_user_proto_init() {
	if File_litellm_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_litellm_v1_user_proto_rawDesc), len(file_litellm_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_litellm_v1_user_proto_goTypes,
		DependencyIndexes: file_litellm_v1_user_proto_depIdxs,
		MessageInfos:      file_litellm_v1_user_proto_msgTypes,
	}.Build()
	File_litellm_v1_user_proto = out.File
	file_litellm_v1_user_proto_goTypes = nil
	file_litellm_v1_user_proto_depIdxs = nil
}
